# Generated by Django 4.1.5 on 2023-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=1000000)),
            ],
        ),
    ]
