# Generated by Django 4.1.5 on 2023-02-02 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_date_post_creation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
